default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  password: holanda

  
development:
  <<: *default
  database: templ_job_board_development
  host: localhost
  username: postgres

test:
  <<: *default
  database: templ_job_board_test

production:
  <<: *default
  database: templ_job_board_production
  username: templ_job_board
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
